FROM rust:latest AS BUILDER

WORKDIR /usr/src/app

COPY . .

RUN cargo build --release

FROM debian:bookworm-slim

COPY --from=BUILDER /usr/src/app/target/release/zero-pii-fincance-calculations /usr/local/bin/zero-pii-fincance-calculations

CMD ["/usr/local/bin/zero-pii-fincance-calculations"]
